export const BAR_LIST_REQUEST = 'BAR_LIST_REQUEST'
export const BAR_LIST_SUCCESS = 'BAR_LIST_SUCCESS'
export const BAR_LIST_FAIL = 'BAR_LIST_FAIL'

export const BAR_DETAILS_REQUEST = 'BAR_DETAILS_REQUEST'
export const BAR_DETAILS_SUCCESS = 'BAR_DETAILS_SUCCESS'
export const BAR_DETAILS_FAIL = 'BAR_DETAILS_FAIL'

export const BAR_DELETE_REQUEST = 'BAR_DELETE_REQUEST'
export const BAR_DELETE_SUCCESS = 'BAR_DELETE_SUCCESS'
export const BAR_DELETE_FAIL = 'BAR_DELETE_FAIL'

export const BAR_CREATE_REQUEST = 'BAR_CREATE_REQUEST'
export const BAR_CREATE_SUCCESS = 'BAR_CREATE_SUCCESS'
export const BAR_CREATE_FAIL = 'BAR_CREATE_FAIL'
export const BAR_CREATE_RESET = 'BAR_CREATE_RESET'

export const BAR_UPDATE_REQUEST = 'BAR_UPDATE_REQUEST'
export const BAR_UPDATE_SUCCESS = 'BAR_UPDATE_SUCCESS'
export const BAR_UPDATE_FAIL = 'BAR_UPDATE_FAIL'
export const BAR_UPDATE_RESET = 'BAR_UPDATE_RESET'

export const BAR_CREATE_REVIEW_REQUEST = 'BAR_CREATE_REVIEW_REQUEST'
export const BAR_CREATE_REVIEW_SUCCESS = 'BAR_CREATE_REVIEW_SUCCESS'
export const BAR_CREATE_REVIEW_FAIL = 'BAR_CREATE_REVIEW_FAIL'
export const BAR_CREATE_REVIEW_RESET = 'BAR_CREATE_REVIEW_RESET'

export const BAR_TOP_REQUEST = 'BAR_TOP_REQUEST'
export const BAR_TOP_SUCCESS = 'BAR_TOP_SUCCESS'
export const BAR_TOP_FAIL = 'BAR_TOP_FAIL'
