export const STALL_LIST_REQUEST = 'STALL_LIST_REQUEST'
export const STALL_LIST_SUCCESS = 'STALL_LIST_SUCCESS'
export const STALL_LIST_FAIL = 'STALL_LIST_FAIL'

export const STALL_DETAILS_REQUEST = 'STALL_DETAILS_REQUEST'
export const STALL_DETAILS_SUCCESS = 'STALL_DETAILS_SUCCESS'
export const STALL_DETAILS_FAIL = 'STALL_DETAILS_FAIL'

export const STALL_DELETE_REQUEST = 'STALL_DELETE_REQUEST'
export const STALL_DELETE_SUCCESS = 'STALL_DELETE_SUCCESS'
export const STALL_DELETE_FAIL = 'STALL_DELETE_FAIL'

export const STALL_CREATE_REQUEST = 'STALL_CREATE_REQUEST'
export const STALL_CREATE_SUCCESS = 'STALL_CREATE_SUCCESS'
export const STALL_CREATE_FAIL = 'STALL_CREATE_FAIL'
export const STALL_CREATE_RESET = 'STALL_CREATE_RESET'

export const STALL_UPDATE_REQUEST = 'STALL_UPDATE_REQUEST'
export const STALL_UPDATE_SUCCESS = 'STALL_UPDATE_SUCCESS'
export const STALL_UPDATE_FAIL = 'STALL_UPDATE_FAIL'
export const STALL_UPDATE_RESET = 'STALL_UPDATE_RESET'

export const STALL_CREATE_REVIEW_REQUEST = 'STALL_CREATE_REVIEW_REQUEST'
export const STALL_CREATE_REVIEW_SUCCESS = 'STALL_CREATE_REVIEW_SUCCESS'
export const STALL_CREATE_REVIEW_FAIL = 'STALL_CREATE_REVIEW_FAIL'
export const STALL_CREATE_REVIEW_RESET = 'STALL_CREATE_REVIEW_STALL'
export const STALL_TOP_SUCCESS = 'STALLTOP_SUCCESS'
export const STALL_TOP_REQUEST = 'STALL_TOP_REQUEST'
export const STALL_TOP_FAIL = 'STALL_TOP_FAIL'
