name: Deployment of FE and BE
# on:
#   branches:[master]
# pull_request:
#   branches:[master]
on: push                    
jobs:
  build:
    runs-on: self-hosted    
    steps: 
    - name: Get code from local to gh runner
      uses: actions/checkout@v3
    - name: Install nodejs 16
      uses: actions/setup-node@v3
      with:                             
        node-version: 16
    - name: Install dependencies
      run: | 
       npm i
       cd frontend
       npm i 
       ci=false && npm run build

    # - name: Copy folder content recursively to remote VPS
    #   uses: garygrossgarten/github-action-scp@release
    #   with:
    #       local: dist
    #       remote: /var/www/www.taraka-uc.com/public_html/
    #       host: ${{ secrets.HOST }}
    #       username: ${{ secrets.USER }}
    #       password: ${{ secrets.PASSWORD }}
