name: Deployment of Front End and Back End
# on:
#   branches:[master]
# pull_request:
#   branches:[master]
on: push
                  
jobs:
  # fix_environment:
  #   environment: raliku
  #   env:
  #     NODE_ENV= ${{ secrets.NODE_ENV }}
  #     PORT= ${{ secrets.PORT }}
  #     MONGO_URI = mongodb+srv://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@nictc.ok4ic.mongodb.net/${{secrets.DB_NAME}}?retryWrites=true&w=majority
  #     JWT_SECRET=${{ secrets.JWT_SECRET }}

  # backend-job:
  #   runs-on: self-hosted    
  #   steps:   
  #   - name: Get code from local to remote runner
  #     uses: actions/checkout@v3
  #   - name: Install nodejs 16
  #     uses: actions/setup-node@v3
  #     with:                             
  #       node-version: 16
  #   - name: Install dependencies for the backend
  #     run: |
  #       npm i
    

      #  CI=false && npm run build


  frontend-job:
    needs: backend-job
    runs-on: self-hosted
    steps: 
    - name: Get code from local to github runner
      uses: actions/checkout@v3
    - name: Install nodejs 16
      uses: actions/setup-node@v3
      with:                             ##configs for nodejs 
        node-version: 16
    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{hashFiles('**/package-lock.json')}} 
    - name: Install dependencies
      run: |
         npm i
         cd frontend
    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{hashFiles('**/package-lock.json')}} 
         npm i
         CI=false npm run build
         
    - name: Copy build folder to hosting location
      uses: garygrossgarten/github-action-scp@release
      with:
          local: build
          remote: /var/www/www.pngondemand.com/public_html/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
       

